### ISSUE TITLE
with blocks: add handling for None (null reference)?

### ISSUE THREAD

**Issue by tjhb** [IronLanguages/ironpython2#205]
Python 'with' blocks are arguably much more valuable in IronPython than in CPython, since it is very common for .NET classes to implement IDisposable, while not so many built-in Python classes currently implement the Content Manager protocol.

The mapping of __enter__ and __exit__ to IDisposable is absolutely great. It allows 'with' blocks in IronPython to reproduce what 'using' blocks do in C#, almost exactly.

But there is an important exception, namely where the result of the with expression is None (a null reference in C#). Here the 'with' block will fail, producing an AttributeError.

For example:
```
def blank():
    return None
repr(blank())
    'None'
with blank():
    pass
```
gives
> Traceback (most recent call last):
>     File "<string>", line 1, in <module>
> AttributeError: 'NoneType' object has no attribute '__exit__'
> 

By contrast, 'using' blocks in C# handle null references implicitly and gracefully.

This is important since it is sometimes difficult to know whether a given function might sometimes potentially return None in advance, especially for a complex function dependent on other functions.

Would it be possible to re-work the IronPython mapping of __enter__ and __exit__ so that None is handled implicitly, without throwing an error?

For a substantial implentation of IronPython where this matters, you might like to see
Radian Studio: http://www.manifold.net
Radian API: http://manifold.net/doc/api/index.html
Radian API discussion: http://www.georeference.org/forum/t135610
Radian also includes a built-in IronPython REPL.

**Comment by mfddev** [comment]
A better URL for Radian API discussion: http://www.georeference.org/forum/t135610#137077

**Comment by slozier** [comment]
Interesting idea. My concern is that this diverges from CPython behavior. Although it seems very unlikely, it would break code like this:
```Python
try:
    with something_that_may_return_none():
        # do something
except AttributeError:
    # do something else
```

**Comment by mfddev** [comment]
The safest option in this regard is to do nothing and just add a wrapper class like SafeNone (perhaps with a different name) discussed in this post:

http://www.georeference.org/forum/t135610#137082

The class would be specific to IronPython / .NET, users of IronPython could then use it without thinking twice.

In a bigger picture, making 'with' itself special-handle None would indeed be a breaking change, but I would argue that the current behavior of throwing on None is atypical while the proposed behavior of gracefully handling it is far more desirable.

Being able to return None instead of a dummy object that will then do "nothing" is a very useful optimization. It avoids tricking the caller into thinking that it got a real object and allows skipping the potentially complex setup / teardown around that object after - which is all a waste of cycles because the object is empty. (For example, in the code snippet in the post linked above, the caller could then have created a table to save the returned records for further processing - only to have no records returned shortly after.) Because of that, calls do end up returning None, and the callers end up having to prepare for it. The only question is whether they have to roll their own classes or can use system classes or can use the protection built into the statement.

**Comment by slozier** [comment]
Throwing on None is atypical in what sense? You can't really compare with to the C# using statement since they have different semantics.

In C# you have
```C#
using(var x = Test()) { }
```
which if written in Python would be equivalent to
```Python
x = Test()
try:
    pass
finally:
    if x is not None:
        x.Dispose()
```

In Python you have
```Python
with test() as x:
    pass
```
which is roughly equivalent to
```Python
t = test()
x = t.__enter__()
try:
    pass
finally:
    t.__exit__()
```

Side note: It looks like this was proposed before in Python: https://mail.python.org/pipermail/python-ideas/2013-August/022731.html.

**Comment by mfddev** [comment]
That 'with' in IronPython works differently from 'using' in C# yet the expectations are that they work the same is exactly why this issue has been posted.

**Comment by slozier** [comment]
The difficulty is that the IronPython `with` can't be both the Python `with` and the C# `using` without breaking compatibility on either side. Since IronPython is primarily a Python implementation with some .NET interop capabilities it makes more sense to follow the Python rules.

While the `using` statement is *designed to properly dispose of an expensive object*, the `with` statement is not, it *is used to wrap the execution of a block with methods defined by a context manager*. (Yes, I know in IronPython it is equivalent to using if the object is `IDisposable`, but `null` is not `IDisposable`). In Python it is very easy to inadvertently return `None` so it does make some sense that `with` would fail on a "None context manager".

(I'm not necessarily opposed to the idea, I'm just playing the devil's advocate to be sure all points of views are covered in the discussion).

**Comment by mfddev** [comment]
I understand that this is a breaking change. It is not for me to say whether to make it or not, you have more information regarding that than me.

I would argue, however, that:

1. The intent of 'with' in Python is the same as the intent of 'using' in C# - to make sure that an expensive object is correctly freed / disposed of / disconnected. That the design of 'with' ended up not handling None naturally is, in my opinion, unintentional and not central to it. What is central is to ensure correct teardown in the face of exceptions. If someone argued for special-casing None when 'with' was being introduced, it would perhaps handle them now.

2. Calls returning None are completely normal. It is unreasonable to expect calls that return a potentially expensive object to always return non-None. Dummy objects returned as a replacement of None aren't a solution it all, they trick callers into doing much more work than they would otherwise do.

As I said, the question isn't whether, as a developer of IronPython / Python code, you will have calls returning None - you will have them, guaranteed. The only question is how you will then handle them. There are the following options: (a) not use 'with', (b) use 'with' with a custom wrapper class (like SafeNone in the example I gave), (c) use 'with' with a wrapper class provided by the framework, (d) have 'with' handle None by itself. To me, (d) looks best, not in the least because 'with' can handle None faster and better than wrapper classes. If / while we can't have (d), I'd argue at least for (c). Without either (d) or (c) the developers start inventing their own wrappers, we all know how this ends up (C++ projects of days past frequently had like five-six versions of strings, all subtly different and uninterchangeable).

But the final decision is obviously in the hands of you and other developers of IronPython and Python.

Thanks for listening.

**Comment by slide** [comment]
In the case of a Python syntax (in this case _with_), we will follow the Python semantics for the operation as much as possible. While we do want to interact with .NET (why else would we work on IronPython), the name of the project is Iron (Implementation RUNs on .NET) Python. We are an implementation of Python, so we need to follow the semantics of Python for the _with_ syntax.

**Comment by moto-timo** [comment]
And should behave as much as possible CPython or the PEP in question... whichever is more sense cal. You can always call a .NET DLL from IronPython if you need other semantics or behavior.

**Comment by mfddev** [comment]
Would you consider adding a helper class to the framework to wrap the value of None, return it on `__enter__` and do nothing on `__exit__`?

For example:

    class SafeNone:
      Value = None
     
      def __init__(self, value):
        self.Value = value
     
      def __enter__(self):
        return self.Value
     
      def __exit__(self, excType, excVal, excTb):
        if not (self.Value is None):
          self.Value.Dispose()
          self.Value = None
        return False # do not stop exceptions

...(perhaps calling `__exit__` instead of `Dispose`, so that we can wrap anything instead of just `IDisposable`).

Then one could use 'with' with calls that can potentially return None like this:

    with SafeNone(CallThatCanReturnNone()) as x:
      ... # x could be None, we can check for this explicitly

Having a helper class provided by the framework will free the devs from rolling their own (if they have to roll their own they will do it differently).

No change to the rules of Python required.

**Comment by slozier** [comment]
Another option:
```Python
class noop(object):
    def __enter__(self): pass
    def __exit__(self, *args): pass
noop = noop()

with CallThatCanReturnNone() or noop as x:
    pass
```

**Comment by tjhb** [comment]
That's elegant but with a downside. It doesn't give us access to the result of the call to CallThatCanReturnNone() if the result is anything evaluating as False.

If the return type is not None (expected) but, say, zero or False (unexpected, possibly indicating a bug) then we lose this information (can't check, we only have a noop) and proceed as for a result of None.

**Comment by slozier** [comment]
Wasn't the point to be able to use `with` like the C# `using` in the case where you may end up with `null`?  The functions can't return something other than an `IDisposable` (or `null`) otherwise your C# code just wouldn't compile. I guess you could do something like the following if you're really worried about other values:
```Python
class _noop(object):
    def __enter__(self): pass
    def __exit__(self, *args): pass

def AllowNone(thing):
    return _noop() if thing is None else thing

with AllowNone(CallThatCanReturnNone()) as x:
    pass
```

**Comment by mfddev** [comment]
I am not sure about `__exit__` taking a variable number of arguments (would you like to silently accept a call to it with twenty arguments? I would prefer failing the call). Other than that, the second variant looks fine to me.

The first doesn't. As mentioned, it makes the check for whether the call indeed succeeded look strange. (You still perform the check inside `using` / `with` when you legitimately expect the call to sometimes fail and are prepared to proceed in a different way if it does, the difference between the current unadorned `with` which forces you to check for None before it and `with` with AllowNone or something similar is that the latter composes the logic better and as a result produces cleaner code.)

**Comment by slide** [comment]
What is the status of this?

**Comment by slide** [comment]
I think the consensus is that this won't be implemented in IronPython, but could he handled in user code if desired.
