### ISSUE TITLE
Newer versions of pip (than bundled in 2.7.8) fail because of pyparsing issue

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#382]
### Prerequisites

* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

When trying to use pip newer than the version supplied with 2.7.8, there is an issue because pyparsing is using f_back and so forth to determine function names. This is not working in IronPython.

### Steps to Reproduce

1. ipy -m ensurepip
2. ipy -m pip install pyserial

**Expected behavior:** 

Pip should function correctly

**Actual behavior:** 

Error about -1 index

### Versions

2.7.8

**Comment by littleq0903** [comment]
**Workaround included**

This is happened not only in pip, also in setuptools or any libs using pyparsing.

It's due to that traceback lib in IronPython could not extract out any stack information (returned empty list instead)

Reference here, also workaround included:
https://github.com/pyparsing/pyparsing/issues/2

The problematic part is in util function which trim the arguments number to specific number, it should be fine with modifying the code directly as a workaround.

Once this got fixed, need to replace the pyparsing version under those libs as well to fix this up.

**Comment by littleq0903** [comment]
Thanks for the quick fix!
