### ISSUE TITLE
Is it possible to use my custom Python environment in ironpython compiler

### ISSUE THREAD

**Issue by Abdalmenem** [IronLanguages/ironpython2#773]
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ ] Are you running the latest version? Yes
* [ ] Are you reporting to the correct repository? Yes
* [ ] Did you perform a cursory search? Yes

### Description

I have installed Ironpython 2.7.11 in order to build GUI for my python code. I want to use all libraries inside used Environment in my python script. For example, I used in my built python script xarray, numpy, pandas, os, system, matplotlib.pyplot and many others. However, ironpython does not have any of these libraries. I have tried to download every single library by following steps (below), but I could not install most of them. It seems, (Not sure), ironpython does not support all python libraries (e.g. xarray, pandas, and matplotlib, skitlearn, and many others).

Kindly, try to answer my three questions

1) Is there any way that can let me use my anaconda env in ironpython instead of downloading libs by cmd?
2) if not, could you please confirm if ironpython should support all python libraries or not?

### Steps to Reproduce

ipy -X:Frames -m ensurepip
ipy -X:Frames -m pip install xarray

**Actual behavior:** [What actually happened]
Failed to download many of my libraries. For example, Xarray
### Versions

2.7.11

**Comment by slozier** [comment]
In theory you can tell IronPython to go and load modules from another folder (e.g. using the IRONPYTHONPATH environment variable, or setting sys.path), however if the modules are not compatible then they'll just fail on import.

Unfortunately, IronPython only supports "pure Python" libraries. In other words it does not support any libraries that make use of the Python/C API. So that means libraries you listed will not work (e.g. numpy, scipy, xarray, pandas, matplotlib, scikit-learn, etc.)

Perhaps [Python.NET](https://github.com/pythonnet/pythonnet) would be better suited for your needs?
